name: Tetris CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: Build and Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        zig-version: [0.13.0]
      fail-fast: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: ${{ matrix.zig-version }}

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install raylib

      - name: Install dependencies (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libraylib-dev

      - name: Build
        run: zig build

      - name: Run tests
        run: zig build test
